# -*- coding: utf-8 -*-
"""Simple Python Code for Describing Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EL9nS3GoT_MXyLdwiuv1NQnOSvZEnLqk
"""

import pandas as pd
from sklearn.datasets import load_iris

import pandas as pd
from sklearn.datasets import load_iris

# Load sample dataset from CSV
data = pd.read_csv("/content/Iris.csv")

# Display first 5 rows
print("FIRST 5 ROWS OF DATASET")
print(data.head())

# Display dataset shape
print("\nDATASET SHAPE")
print(data.shape)

# Display column names
print("\nCOLUMN NAMES")
print(data.columns)

# Statistical description
print("\nSTATISTICAL SUMMARY")
print(data.describe())

# Check missing values
print("\nMISSING VALUES")
print(data.isnull().sum())